### ISSUE TITLE
Unable to get it running using optionB.

### ISSUE THREAD

**Issue by Phrenzy** [donbing/bitbot#46]
- I used Raspberry Pi Imager to install Raspberry Pi OS Lite (32bit).

- I added ssh and wifi config files to the microSD card.

- I put the microSD card into a Pi Zero W and booted it up.

- I followed the steps in section B on: https://github.com/donbing/bitbot/blob/main/docs/app_install.md

- During step 2 I got errors suggesting I add the /home/pi/.local/bin folder to the PATH

    I ran step 4 and got the following errors:
~~~~
    Traceback (most recent call last):
      File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
       return _run_code(code, main_globals, None,
      File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
     File "/home/pi/bitbot/run.py", line 13, in <module>
        from src.bitbot import BitBot
      File "/home/pi/bitbot/src/bitbot.py", line 1, in <module>
        from PIL import Image
      File "/home/pi/.local/lib/python3.9/site-packages/PIL/Image.py", line 69, in <module>
        from . import _imaging as core
    ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory
~~~~
I added the above folder to PATH and I got the same errors.

I was able to use Setup Option A successfully.

**Comment by donbing** [comment]
Thanks for talking the time to write this, looks like the instructions are a little out of date. (Its missing some of the required apt packages) ill get it updated.
